Aurelien/crowded markers map
erwan-haquet/harvest-live-front pull request #6
Opened 2019-08-22 15:55 UTC by Morzanne

-adding functionalities => reassigning new coordinates
                                   => updating the news observations markers with the new coordinates
-displaying the new observations on the map
-Refactoring on the new filtering system to filter the markers by cultures on the map
- Refactoring some folder in order to provide a better architecture

2019-08-23 12:14 UTC, maallard requested changes
Cf commentaires

2019-08-26 07:07 UTC, Morzanne commented on src/components/observation/Filters/FiltersContainer.js
> +    console.log(selectedCulture)
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/Map/index.jsx
>          <WheatMarkerListContainer />
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/observation/BarleyObservation/MarkerList/MarkerListContainer.js
> +    return null;
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/observation/CornObservation/MarkerList/MarkerListContainer.js
> +    return null;
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/observation/RapeseedObservation/MarkerList/MarkerListContainer.js
> +    return null;
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/observation/SunflowerObservation/MarkerList/MarkerListContainer.js
> +    return null;
Done

2019-08-26 08:10 UTC, Morzanne commented on src/components/observation/WheatObservation/MarkerList/MarkerListContainer.js
> +    return null;
Done

2019-08-26 08:13 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/index.jsx
> +const ObservationsClusterMarkers = ({ observations, selectedCulture }) =>
Done

2019-08-26 08:56 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +        return <Observation observation={cluster.first()} selectedCulture={selectedCulture} />;
Done

2019-08-26 08:59 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +    var culturesOrderedByCoordinates = immutable
Done

2019-08-26 09:02 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +      .fromJS(allCulturesObservations(selectedCulture))
Done

2019-08-26 09:04 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +    var culturesOrderedByCoordinates = immutable
Done

2019-08-26 09:09 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +    const mappedCultures = culturesOrderedByCoordinates.map(cluster => {
Done

2019-08-26 09:49 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +    var reassignedListWithNewCoords = this.applyMarkersNewCoordinates(
Done

2019-08-26 09:49 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +    for (let i = 0; i < nbPoints; i++) {
Done

2019-08-26 09:50 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +  selectedCulture: getSelectedCulture(state)
Done

2019-08-26 11:41 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +  selectedCulture: getSelectedCulture(state)
Done

2019-08-26 11:42 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +    var reassignedListWithNewCoords = this.applyMarkersNewCoordinates(
Done

2019-08-26 12:23 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +    const allCulturesObservations = (selectedCulture) => {
Done

2019-08-26 12:29 UTC, Morzanne commented on src/components/observation/ObservationsMarkers/ObservationsListContainer.js
> +      return <MarkerClusterContainer observations={cluster} selectedCulture={selectedCulture} />;
Done

2019-08-26 14:48 UTC, maallard commented on src/components/Map/index.jsx
> +        <MarkerClusterContainer />
à quoi sert ce composant ?

2019-08-27 08:27 UTC, Morzanne commented on src/components/Map/index.jsx
> +        <MarkerClusterContainer />
A pas grand chose en effet il est contenu dans <ObservationsListContainer />, je le retire

2019-08-27 13:58 UTC, erwan-haquet requested changes
Le reste est good :+1:

2019-08-27 13:58 UTC, erwan-haquet commented on src/components/observation/Observation/index.jsx
> +export default Observation;
Le but de ce component n'est pas de faire de l'affichage mais bien de la logique, tu dois utiliser un `Container`. Aussi le nommage n'est pas assez précis, `Observation` ou `ObservationContainer` peut faire référence à la description d'une observation, un marqueur d'observation, l'ajout d'une observation... ici tu veux son role c'est de display un marqueur donc `ObservationMarkerContainer` me semble correct.

2019-08-27 13:58 UTC, erwan-haquet commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +export default connect()(MarkerClusterContainer);
tu n'as pas besoins de connecter le component.

2019-08-27 13:58 UTC, erwan-haquet commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +class MarkerClusterContainer extends Component {
Le nom du container doit reprendre le nom de son dossier, le dossier représente la globalité du component, le container represente une partie précise de ce component.

2019-08-27 13:58 UTC, erwan-haquet commented on src/components/observation/ObservationsClusterMarkers/index.jsx
> +const ObservationsClusterMarkers = ({ observations }) =>
La convention utilisé pour le nommage des liste est `ObservationsClusterMarkerList` et non `ObservationsClusterMarkers`.

2019-08-27 13:58 UTC, erwan-haquet commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +class MarkerClusterContainer extends Component {
pour le nommage voir le commentaire sur `ObservationsClusterMarkers`

2019-08-30 08:28 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +export default connect()(MarkerClusterContainer);
Done

2019-08-30 08:38 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/index.jsx
> +const ObservationsClusterMarkers = ({ observations }) =>
Done

2019-08-30 08:53 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +class MarkerClusterContainer extends Component {
Done

2019-08-30 12:05 UTC, Morzanne commented on src/components/observation/ObservationsClusterMarkers/MarkerClusterContainer.js
> +class MarkerClusterContainer extends Component {
Done

2019-08-30 12:45 UTC, maallard commented on src/components/observation/Observation/index.jsx
> +  var updatedIconUrl = null;
Nous n'utilisons pas de `var`, utilise `let` ou `const`

2019-08-30 12:47 UTC, erwan-haquet approved these changes

2019-08-30 12:47 UTC, maallard requested changes
À fixer

2019-09-02 07:29 UTC, Morzanne commented on src/components/observation/Observation/index.jsx
> +  var updatedIconUrl = null;
Done

2019-09-04 07:26 UTC, maallard approved these changes

2019-09-04 07:27 UTC, merged